sudo: false
language: node_js
cache: npm
notifications:
  email: false
node_js: '10'
jobs:
  include:
    - stage: test
      os: linux
      script: echo "done linux"
    - stage: test_head_repo
      os: linux
      script: echo "done test_repo linux"
      if: head_repo = repo
    - stage: test_repo_exact
      os: linux
      script: echo "done test_repo_exact linux"
      if: repo = InvictusMB/travis-ci-win-test
    - stage: test_head_repo_exact
      os: linux
      script: echo "done test_head_repo_exact linux"
      if: head_repo = InvictusMB/travis-ci-win-test
    - stage: test_head_repo_present
      os: linux
      script: echo "done test_head_repo_present linux"
      if: head_repo IS present
branches:
  only: master

